[features]
resolution = true
skip-lint = false

[programs.localnet]
insurance_contract = "InsuranceContract1111111111111111111111111111"

[programs.devnet]
insurance_contract = "InsuranceContract1111111111111111111111111111"

[programs.mainnet]
insurance_contract = "InsuranceContract1111111111111111111111111111"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[test.validator]
url = "https://api.devnet.solana.com"

[[test.validator.clone]]
address = "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s"

[[test.validator.clone]]
address = "noopb9bkMVfRPU8AsbpTUg8AQkHtKwMYZiFUjNRtMmV"